# Generated by Django 5.2 on 2026-09-19 21:02

import Decoration.built_in_func
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Decoration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='Cover_Image',
            field=models.ImageField(upload_to=Decoration.built_in_func.item_image_upload_to),
        ),
        migrations.AlterField(
            model_name='package',
            name='image',
            field=models.ImageField(upload_to=Decoration.built_in_func.package_image_upload_to),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=Decoration.built_in_func.profile_picture_upload_to),
        ),
    ]
