# Generated by Django 5.0.3 on 2024-08-19 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Decoration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='decoration_packages',
            name='location',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='decoration_packages',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='decoration_packages',
            name='image',
            field=models.ImageField(upload_to='decorations/packages'),
        ),
        migrations.AlterField(
            model_name='decoration_packages',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='decoration_packages',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
