# Generated by Django 5.0.3 on 2024-08-24 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Decoration', '0002_decoration_packages_location_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Decoration_Items',
            fields=[
                ('Item_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=255)),
                ('Price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Available_Quantity', models.IntegerField()),
                ('Cover_Image', models.ImageField(upload_to='decoration_images/')),
                ('Location', models.CharField(max_length=255)),
            ],
        ),
    ]
