# Generated by Django 5.0.3 on 2024-08-24 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Decoration', '0003_decoration_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decoration_items',
            name='Cover_Image',
            field=models.ImageField(upload_to='decorations/items'),
        ),
    ]
