# Generated by Django 5.0.3 on 2024-08-27 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Decoration', '0004_alter_decoration_items_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='decoration_items',
            name='Catagory',
            field=models.CharField(default='General', max_length=100),
        ),
    ]
