# Generated by Django 5.0.3 on 2024-08-27 19:21

import Decoration.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Decoration', '0005_decoration_items_catagory'),
    ]

    operations = [
        migrations.AddField(
            model_name='decoration_items',
            name='available_from',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='decoration_items',
            name='available_to',
            field=models.DateField(default=Decoration.models.get_default_available_to),
        ),
        migrations.AddField(
            model_name='decoration_packages',
            name='available_from',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='decoration_packages',
            name='available_to',
            field=models.DateField(default=Decoration.models.get_default_available_to),
        ),
    ]
