# Generated by Django 5.0.3 on 2024-08-29 19:27

from django.db import migrations, models
import django.db.models.deletion
from django.db.models import F

def set_default_package_id(apps, schema_editor):
    Decoration_Packages = apps.get_model('Decoration', 'Decoration_Packages')
    for index, package in enumerate(Decoration_Packages.objects.all(), start=1):
        package.package_id = index
        package.save()

class Migration(migrations.Migration):

    dependencies = [
        ('Decoration', '0006_decoration_items_available_from_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='decoration_packages',
            name='id',
        ),
        migrations.AddField(
            model_name='decoration_packages',
            name='package_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.RunPython(set_default_package_id),
        migrations.CreateModel(
            name='DecorationMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], max_length=10)),
                ('file', models.FileField(upload_to='decorations/media/')),
                ('decoration_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='Decoration.decoration_packages')),
            ],
        ),
    ]
