# Generated by Django 5.0.3 on 2024-08-29 19:44

import Decoration.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Decoration', '0007_remove_decoration_packages_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='decorationmedia',
            name='title',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AlterField(
            model_name='decorationmedia',
            name='file',
            field=models.FileField(upload_to=Decoration.models.upload_to),
        ),
    ]
