# Generated by Django 5.0.3 on 2024-08-30 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Decoration', '0009_rename_title_decorationmedia_items_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerInfo',
            fields=[
                ('Customer_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=255)),
                ('Email', models.EmailField(max_length=255)),
                ('Password', models.CharField(max_length=128)),
                ('Phone_No', models.CharField(max_length=20, null=True)),
                ('District', models.CharField(max_length=100, null=True)),
                ('Thana', models.CharField(max_length=100, null=True)),
                ('Address', models.TextField(null=True)),
            ],
        ),
    ]
