# Generated by Django 5.0.3 on 2024-08-30 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Decoration', '0010_customerinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Decoration_Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField()),
                ('review', models.TextField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Decoration.customerinfo')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Decoration.decoration_packages')),
            ],
        ),
    ]
