# Generated by Django 5.1.1 on 2024-09-08 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Decoration', '0011_decoration_review'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomerInfo',
            new_name='Customer',
        ),
        migrations.RenameModel(
            old_name='decoration_packages',
            new_name='Packages',
        ),
    ]
