# Generated by Django 5.1.1 on 2024-09-08 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Decoration', '0012_rename_customerinfo_customer_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Decoration_Items',
            new_name='Item',
        ),
        migrations.RenameModel(
            old_name='Packages',
            new_name='Package',
        ),
    ]
