# Generated by Django 5.1.1 on 2024-09-08 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Decoration', '0013_rename_decoration_items_item_rename_packages_package'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Decoration_Review',
            new_name='Review',
        ),
    ]
