# Generated by Django 5.1.1 on 2024-09-08 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Decoration', '0016_alter_package_detail_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package_detail',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item_details', to='Decoration.item'),
        ),
    ]
