# Generated by Django 5.1.1 on 2024-09-08 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Decoration', '0017_alter_package_detail_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_Catagory',
            fields=[
                ('catagory_id', models.AutoField(primary_key=True, serialize=False)),
                ('catagory_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='package',
            name='Catagory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Decoration.product_catagory'),
        ),
    ]
