# Generated by Django 5.1.1 on 2024-09-08 07:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Decoration', '0018_product_catagory_package_catagory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='package',
            old_name='Catagory',
            new_name='Product_Catagory',
        ),
        migrations.AddField(
            model_name='item',
            name='Product_Catagory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Decoration.product_catagory'),
        ),
    ]
