# Generated by Django 5.0.3 on 2024-09-11 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Decoration', '0019_rename_catagory_package_product_catagory_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='Item_ID',
            new_name='ID',
        ),
        migrations.RenameField(
            model_name='package',
            old_name='package_id',
            new_name='ID',
        ),
    ]
