# Generated by Django 5.0.3 on 2024-09-13 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Decoration', '0021_rename_id_item_item_id_rename_id_package_package_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.BooleanField(default=True)),
                ('pack_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='Decoration.package')),
            ],
        ),
    ]
