# Generated by Django 5.0.3 on 2024-09-15 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Decoration', '0024_order_info'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order_Info',
        ),
    ]
