# Generated by Django 5.0.3 on 2024-10-09 21:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Decoration', '0027_order_info_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_info',
            name='order_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.CreateModel(
            name='Order_Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items_quantity', models.IntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Decoration.item')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Decoration.order_info')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Decoration.package')),
            ],
        ),
    ]
