# Generated by Django 5.0.3 on 2024-10-10 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Decoration', '0028_order_info_order_date_order_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_detail',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Decoration.item'),
        ),
        migrations.AlterField(
            model_name='order_detail',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Decoration.package'),
        ),
        migrations.AlterField(
            model_name='order_info',
            name='order_date',
            field=models.DateField(null=True),
        ),
    ]
