# Generated by Django 5.0.3 on 2024-10-10 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Decoration', '0029_alter_order_detail_item_alter_order_detail_package_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_info',
            name='order_id',
            field=models.BigIntegerField(editable=False, primary_key=True, serialize=False),
        ),
    ]
