# Generated by Django 5.0.3 on 2024-10-10 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Decoration', '0030_alter_order_info_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='order_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
