# Generated by Django 5.0.3 on 2024-10-12 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Decoration', '0033_alter_profile_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='packageavailability',
            old_name='date',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='packageavailability',
            old_name='pack_id',
            new_name='package',
        ),
        migrations.RemoveField(
            model_name='item',
            name='available_from',
        ),
        migrations.RemoveField(
            model_name='item',
            name='available_to',
        ),
        migrations.RemoveField(
            model_name='package',
            name='available_from',
        ),
        migrations.RemoveField(
            model_name='package',
            name='available_to',
        ),
        migrations.RemoveField(
            model_name='packageavailability',
            name='status',
        ),
        migrations.AddField(
            model_name='packageavailability',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ItemAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='Decoration.item')),
            ],
        ),
    ]
