# Generated by Django 5.0.3 on 2024-10-12 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Decoration', '0034_rename_date_packageavailability_end_date_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PackageAvailability',
            new_name='PackageBooked',
        ),
        migrations.AlterField(
            model_name='package_detail',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Pack_Details', to='Decoration.package'),
        ),
        migrations.CreateModel(
            name='ItemBooked',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField()),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='Decoration.item')),
            ],
        ),
        migrations.DeleteModel(
            name='ItemAvailability',
        ),
    ]
