# Generated by Django 5.0.3 on 2024-10-23 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Decoration', '0035_rename_packageavailability_packagebooked_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='client/profile_pictures'),
        ),
    ]
