# Generated by Django 5.0.3 on 2024-10-24 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Decoration', '0037_remove_profile_profile_picture_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='client/profile_pictures'),
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
